---
driver:
  name: dokken
  chef_version: current
  privileged: true
  
transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec
    
platforms:
- name: default
  driver:
    image: dokken/ubuntu-16.04
    pid_one_command: /bin/systemd
    
suites:
  - name: default
    run_list:
    - recipe[dokken-demo::default]
